### ISSUE TITLE
Role Detail page - descending characters cut off

### ISSUE THREAD

**Issue by Karvel** [EditLLC/montage-frontend#52]
![screen shot 2016-07-25 at 2 22 36 pm](https://cloud.githubusercontent.com/assets/488032/17117981/82b0cfe0-5273-11e6-914e-3f92afcbe78f.png)

Does not appear to be an issue in Firefox. Is present in Chrome and Safari.

**Comment by juliancoleman** [comment]
can you give me the class of that text?

edit: never mind. I got it

**Comment by juliancoleman** [comment]
adding a `6px` bottom margin fixes this issue. I'll leave that up for discussion
