### ISSUE TITLE
Mixing of query results

### ISSUE THREAD

**Issue by nick-herrera** [EditLLC/montage-frontend#64]
When executing a second query in the record browser, the results of the second query are combined with the results of the first query for a split second.

![image](https://cloud.githubusercontent.com/assets/13726377/17428068/557b6538-5a9a-11e6-91db-d0c1abb759da.png)

**Comment by juliancoleman** [comment]
I am unable to replicate this issue in Safari and Chrome, even with throttling down to `Regular 2G`.

**Comment by nick-herrera** [comment]
Agreed. It seems to be resolved now.
