### ISSUE TITLE
Query Builder Error Messages

### ISSUE THREAD

**Issue by juliancoleman** [EditLLC/montage-frontend#71]
It looks like we are getting the following errors in the `montage-notifications` channel on Slack

"HTTP Errors" search found 2 matches — https://papertrailapp.com/heroku/go/119069313?a=app37540145&app=montage-live&search_id=6005053

``` scala
Sep 12 13:22:38 montage-live heroku/router:
at=error
code=H13
desc="Connection closed without response"
method=POST
path="/api/v1/execute/"
host=aggregator.mntge.com
request_id=101b014a-9f75-4d5a-95f9-c02024deb120
fwd="209.136.228.130"
dyno=web.1
connect=0m
service=29732ms
status=503
bytes=0 

Sep 12 13:23:08 montage-live heroku/router:
at=error
code=H13
desc="Connection closed without response"
method=POST
path="/api/v1/execute/"
host=aggregator.mntge.com
request_id=ce1f6385-9cdb-4640-bcca-f7ed283ec37c
fwd="209.136.228.130"
dyno=web.2
connect=2ms
service=29247ms
status=503
bytes=0 
```

Whatever changes were made to the API, query builder filters will time out without giving a user-friendly message. It actually doesn't do much at all other than console that the network connection was lost

**Comment by nick-herrera** [comment]
This may not have been the result of changes to the backend. It could simply be that we didn't time out on previous requests.

@juliancoleman Do _all_ filters time out?

**We should display an error message for failed queries.**

**Comment by juliancoleman** [comment]
I just tested... `00004` is not a valid search query, as there are no results with this sequence of digits. The one I was thinking of was `0004`, which works. So, it looks like we just need to pass some sort of message if the query didn't return anything, or if no results were found.

**Comment by nick-herrera** [comment]
Reopening. This is still a bug that needs to be fixed since there is no error message displayed to the user.
